name: Haskell CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test:
    runs-on: codeberg-small

    steps:
      - uses: actions/checkout@v4

      - name: Install Stack
        run: |
          curl -sSL https://get.haskellstack.org/ | sh

      - name: Test
        run: stack test
